#!/bin/bash
### BEGIN INIT INFO
# Provides:          motd_stat
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts motd_stat
# Description:       Starts motd_stat using start-stop-daemon
### END INIT INFO


NAME=motd_stat
DESC="Network statistic analyzer for the MOTD"
PID_FILE=/var/run/$NAME.pid
DAEMON=/etc/motd_stat.py
DAEMON_OPTS=""

test -x $DAEMON || exit 0


set -e

case "$1" in
    start)
        echo -n "Starting $DESC: "
        if start-stop-daemon --start --pidfile $PID_FILE --make-pidfile --background --startas $DAEMON -- $DAEMON_OPTS
        then
            echo -e "OK"
        else
            echo -e "FAIL"
        fi
        ;;
    stop)
        echo -n "Stopping $DESC: "
        if start-stop-daemon --stop --pidfile $PID_FILE
        then
            echo -e "OK"
        else
            echo -e "FAIL"
        fi
        ;;
    restart|force-reload)
        ${0} stop
        sleep 0.5
        ${0} start
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
